baseURL = "/"
languageCode = "en-us"
title = "Untargeted Metabolomics Workflow"
description = "Workflow for processing and analysis of MALDI, DI-MS, LC-MS data using open source tools and software"
pygmentsUseClasses=true
enableEmoji = true
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$", "index\\.html", '\.knit\.md$', '\.utf8\.md$']


[module]
  [[module.imports]]
    path = "github.com/matcornic/hugo-theme-learn"
  [[module.imports]]
    path = "github.com/dzello/reveal-hugo"

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true

[outputs]
home = [ "HTML", "RSS", "JSON"]

[Languages]
[Languages.en]
title = "Untargeted Metabolomics Workflow"
weight = 1
languageName = "English"

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> GitHub repo"
identifier = "ds"
url = "https://github.com/LizzyParkerPannell/Untargeted_metabolomics_workflow"
weight = 10

[[Languages.en.menu.shortcuts]]
name = "<i class='fa fa-map' style='color: white'></i> Workflow Diagram"
url = "https://untargeted-metabolomics-workflow.netlify.app/00_overview/05_workflow-diagram/"
weight = 20

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-fw fa-bullhorn'></i> Credits"
url = "/credits"
weight = 30

[[Languages.en.menu.shortcuts]]
name = "<i class='fa fa-certificate'></i> CC-BY Licence"
url = "https://creativecommons.org/licenses/by/4.0/"
weight = 40

[params]
  editURL = false
  description = "Workflow for processing and analysis of MALDI, DI-MS, LC-MS data using open source tools and software"
  author = "Elizabeth Parker"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false
  themeVariant = "rse-learn"

[markup]
  [markup.highlight]
    # if `guessSyntax = true`, there will be no unstyled code even if no language
    # was given BUT Mermaid and Math codefences will not work anymore! So this is a
    # mandatory setting for your site if you want to use Mermaid codefences
    guessSyntax = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params.reveal_hugo]
 theme = "white"
 load_default_plugins = false
 plugins = [
   "reveal-js/plugin/zoom-js/zoom.js",
   "reveal-js/plugin/notes/notes.js",
 ]
